"""Migration after profile codev3

Revision ID: 888eec232951
Revises: 35592279b3fb
Create Date: 2020-07-13 17:20:33.425050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888eec232951'
down_revision = '35592279b3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    # ### end Alembic commands ###
